service: ce6-joannew-12sept-sls
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1

functions:
  api:
    handler: handler.handler
    environment:
      CLASS_NAME: "CE 6-Joannew"
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    DelfrinandoEmailSns:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: joannew-email-topic
        Subscription: 
          - Protocol: "email"
            Endpoint: "joanne.0326@gmail.com"


plugins:
  - serverless-offline